### ISSUE TITLE
El ejecutable se cuelga al hacer doble click sobre la cara de Adso al principio

### ISSUE THREAD

**Issue by federicopeinado** [nvidiosin/isoAbbeyTFG#24]
Me ha pasado al poco de arrancar la versión del 13 de julio... me moví un poco con Guillermo, y enseguida intenté cambiar a Adso... como no funcionaba le di varias veces y el ejecutable crasheo :-(

**Comment by nvidiosin** [comment]
El problema es que la primera vez que se pulsa a una casilla a la que no te puedes mover se cuelga durante unos 3 segundos. Al pulsar sobre Adso nada mas comenzar estas pulsando sobre una casilla exterior, esto es problema de IsoUnity y los gemelos ya estan avisados
